/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check: answers as soon as the API process is up.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Ends this browser's session. Works (and does nothing) when already logged out.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_account_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Account
         * @description Deletes the user and, through the database's cascades, everything that belongs to them,
         *     then their uploaded files.
         */
        delete: operations["delete_account_api_account_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload Document */
        put: operations["upload_document_api_documents__kind__put"];
        post?: never;
        /** Delete Document */
        delete: operations["delete_document_api_documents__kind__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_profile_get"];
        /** Save Profile */
        put: operations["save_profile_api_profile_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Options */
        get: operations["options_api_profile_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discover/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Options */
        get: operations["options_api_discover_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discover/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search */
        post: operations["search_api_discover_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/opportunities/{opportunity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Opportunity */
        get: operations["opportunity_api_opportunities__opportunity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_document_api_documents__kind__put */
        Body_upload_document_api_documents__kind__put: {
            /** File */
            file: string;
        };
        /** DeleteAccountIn */
        DeleteAccountIn: {
            /** Password */
            password: string;
        };
        /** DiscoverOptions */
        DiscoverOptions: {
            /** Types */
            types: string[];
            /** Disciplines */
            disciplines: string[];
            /** Countries */
            countries: string[];
        };
        /** DocumentOut */
        DocumentOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "cv" | "statement" | "portfolio";
            /** File Name */
            file_name: string;
            /** Size Bytes */
            size_bytes: number;
            /** Chunk Count */
            chunk_count: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** DocumentSuggestions */
        DocumentSuggestions: {
            /** Documents */
            documents: components["schemas"]["SourceDocument"][];
            /** Items */
            items: components["schemas"]["Suggestion"][];
        };
        /** Evidence */
        Evidence: {
            /** Quote */
            quote: string;
            /** Citation */
            citation: string;
            /** Source */
            source?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** OpportunityOut */
        OpportunityOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Organisation */
            organisation: string | null;
            /** Types */
            types: string[];
            /** City */
            city: string | null;
            /** Countries */
            countries: string[];
            /** Deadline */
            deadline: string | null;
            /** Funding */
            funding: string;
            /** Funded */
            funded: boolean;
            /** Fee */
            fee: string;
            /** Description */
            description: string | null;
            /** Source Url */
            source_url: string;
            verdict: components["schemas"]["VerdictOut"];
            /** Profile Filled */
            profile_filled: boolean;
        };
        /** Option */
        Option: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** Options */
        Options: {
            /** Countries */
            countries: components["schemas"]["Option"][];
            /** Disciplines */
            disciplines: string[];
            /** Career Stages */
            career_stages: string[];
        };
        /** PasswordChangeIn */
        PasswordChangeIn: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** ProfileIn */
        ProfileIn: {
            values: components["schemas"]["ProfileValues"];
            /**
             * Evidence
             * @default {}
             */
            evidence: {
                [key: string]: components["schemas"]["Evidence"];
            };
            /**
             * Reviewed Documents
             * @default []
             */
            reviewed_documents: string[];
        };
        /** ProfileOut */
        ProfileOut: {
            values: components["schemas"]["ProfileValues"];
            /**
             * Evidence
             * @default {}
             */
            evidence: {
                [key: string]: components["schemas"]["Evidence"];
            };
            /** Updated At */
            updated_at?: string | null;
            suggestions?: components["schemas"]["DocumentSuggestions"] | null;
        };
        /**
         * ProfileValues
         * @description ArtistProfile as the artist fills it in. Every field optional; empty never rejects a call.
         *     Each check is attached to its field, so the form can show the message next to it.
         */
        ProfileValues: {
            /** Birth Date */
            birth_date?: string | null;
            /**
             * Nationalities
             * @default []
             */
            nationalities: string[];
            /** Residence Country */
            residence_country?: string | null;
            /** Applicant Type */
            applicant_type?: ("individual" | "group" | "organisation") | null;
            /**
             * Disciplines
             * @default []
             */
            disciplines: string[];
            /** Career Stage */
            career_stage?: string | null;
            /** Active Since */
            active_since?: number | null;
            /** Currently Enrolled */
            currently_enrolled?: boolean | null;
            /** Graduation Year */
            graduation_year?: number | null;
            /** Has Degree */
            has_degree?: boolean | null;
            /** Degree Field */
            degree_field?: string | null;
        };
        /** RequirementOut */
        RequirementOut: {
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "FAIL" | "CHECK" | "PASS";
            /** Topic */
            topic: string;
            /** Reason */
            reason: string;
        };
        /** ResultOut */
        ResultOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Organisation */
            organisation: string | null;
            /** Types */
            types: string[];
            /** City */
            city: string | null;
            /** Countries */
            countries: string[];
            /** Deadline */
            deadline: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ELIGIBLE" | "CHECK" | "LIKELY_NOT_ELIGIBLE";
            /** Reason */
            reason: string;
            /** Score */
            score: number | null;
        };
        /** SearchIn */
        SearchIn: {
            /**
             * Mode
             * @default matched
             * @enum {string}
             */
            mode: "matched" | "all";
            /**
             * Text
             * @default
             */
            text: string;
            /**
             * Types
             * @default []
             */
            types: string[];
            /**
             * Disciplines
             * @default []
             */
            disciplines: string[];
            /** Country */
            country?: string | null;
            /**
             * Funded Only
             * @default false
             */
            funded_only: boolean;
            /**
             * No Fee
             * @default false
             */
            no_fee: boolean;
        };
        /** SearchOut */
        SearchOut: {
            /** Results */
            results: components["schemas"]["ResultOut"][];
            /** Total */
            total: number;
            /**
             * Order
             * @enum {string}
             */
            order: "match" | "deadline";
            /** Ranked By */
            ranked_by: string[];
            /** Profile Filled */
            profile_filled: boolean;
        };
        /** SentenceOut */
        SentenceOut: {
            /** Quote */
            quote: string;
            /** Requirements */
            requirements: components["schemas"]["RequirementOut"][];
        };
        /** SignupIn */
        SignupIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** SourceDocument */
        SourceDocument: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** File Name */
            file_name: string;
        };
        /** Suggestion */
        Suggestion: {
            /** Field */
            field: string;
            /** Value */
            value: unknown;
            /** Quote */
            quote: string;
            /** Citation */
            citation: string;
            /** Note */
            note?: string | null;
            /** Source */
            source: string;
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerdictOut */
        VerdictOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ELIGIBLE" | "CHECK" | "LIKELY_NOT_ELIGIBLE";
            /** Summary */
            summary: string;
            /** Fails */
            fails: number;
            /** Checks */
            checks: number;
            /** Passes */
            passes: number;
            /** Sentences */
            sentences: components["schemas"]["SentenceOut"][];
            /** Commitments */
            commitments: string[];
            /** About Project */
            about_project: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    signup_api_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    change_password_api_account_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_api_account_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"][];
                };
            };
        };
    };
    upload_document_api_documents__kind__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "cv" | "statement" | "portfolio";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_documents__kind__put"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_documents__kind__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "cv" | "statement" | "portfolio";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
        };
    };
    save_profile_api_profile_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    options_api_profile_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Options"];
                };
            };
        };
    };
    options_api_discover_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverOptions"];
                };
            };
        };
    };
    search_api_discover_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    opportunity_api_opportunities__opportunity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                opportunity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpportunityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
